# SYSTEM OF LINEAR EQUATIONS

$3x+4y=7$

$4x+5y=9$

In [1]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

In [2]:
from sympy.abc import x,y

In [3]:
eq1=sp.Eq(3*x+4*y,7)
eq2=sp.Eq(4*x+5*y,9)

In [4]:
eq1

Eq(3*x + 4*y, 7)

In [5]:
eq2

Eq(4*x + 5*y, 9)

In [6]:
#solving the system of linear equations
sp.solve((eq1,eq2),(x,y))

{x: 1, y: 1}

In [8]:
#USING NUMPY TO SOLVE
#AX=b
A=np.array([[3,4],[4,5]])
b=np.array([7,9])

In [10]:
np.linalg.solve(A,b)

array([1., 1.])

In [11]:
np.linalg.inv(A)

array([[-5.,  4.],
       [ 4., -3.]])


solve the system of linear equations
$4x-y+2z=7$

$x+3y+5x=16$

$2x+3y-4z=9$

In [14]:
A=np.array([[4,-1,2],[1,3,5],[2,3,-4]])
b=np.array([7,16,9])

In [15]:
np.linalg.solve(A,b)

array([2., 3., 1.])